
import exp2.condb;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class add_member extends javax.swing.JFrame {

    /**
     * Creates new form add_member
     */
    public add_member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        members_name_label = new javax.swing.JLabel();
        initial_deposit = new javax.swing.JTextField();
        contact_number_label = new javax.swing.JLabel();
        deposit_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deposit_label1 = new javax.swing.JLabel();
        member_name = new javax.swing.JTextField();
        contact_number = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_name_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        members_name_label.setForeground(new java.awt.Color(242, 242, 242));
        members_name_label.setText("Members name       :");
        jPanel1.add(members_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 40));

        initial_deposit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel1.add(initial_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 230, 30));

        contact_number_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        contact_number_label.setForeground(new java.awt.Color(242, 242, 242));
        contact_number_label.setText("Contact number      :");
        jPanel1.add(contact_number_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 185, 180, 30));

        deposit_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        deposit_label.setForeground(new java.awt.Color(242, 242, 242));
        deposit_label.setText("Email                          :");
        jPanel1.add(deposit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 180, 30));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Add member");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 110, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Add member");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 200, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        deposit_label1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        deposit_label1.setForeground(new java.awt.Color(242, 242, 242));
        deposit_label1.setText("Initial Deposit          :");
        jPanel1.add(deposit_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 180, 30));

        member_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        member_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_nameActionPerformed(evt);
            }
        });
        jPanel1.add(member_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 230, 30));

        contact_number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel1.add(contact_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 230, 30));

        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 230, 30));

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Boolean flag = false;
        String mem_name = initial_deposit.getText();
        String contact_no = contact_number.getText();
        String mail = email.getText();
        String deposit=initial_deposit.getText();
        
        
        if(mem_name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "You didn't insert members name!");
        }
        
        else if(contact_no.equals(""))
        {
            JOptionPane.showMessageDialog(null, "You didn't insert members contact number!");
        }
        
        else if(deposit.equals(""))
        {
            JOptionPane.showMessageDialog(null, "You didn't insert members initial deposit!");
        }
        
        else
        {
            try {
            
            String query = "INSERT INTO member(name,contact_number,deposit,email) values('"+mem_name+"','"+contact_no+"','"+deposit+"','"+mail+"')";
            Connection con = condb.getCon();
            Statement stm = con.createStatement();
            int x = stm.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Successfully added member");
            home_page obj = new home_page();
            obj.setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void member_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        home_page obj=new home_page();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact_number;
    private javax.swing.JLabel contact_number_label;
    private javax.swing.JLabel deposit_label;
    private javax.swing.JLabel deposit_label1;
    private javax.swing.JTextField email;
    private javax.swing.JTextField initial_deposit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField member_name;
    private javax.swing.JLabel members_name_label;
    // End of variables declaration//GEN-END:variables
}
