
import exp2.condb;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;


public class create_account extends javax.swing.JFrame {

    /**
     * Creates new form create_account
     */
    public create_account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username_label = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        password_label1 = new javax.swing.JLabel();
        confirm_pass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        q_1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        q_2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        q_3 = new javax.swing.JTextField();
        create_acc_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username_label.setForeground(new java.awt.Color(242, 242, 242));
        username_label.setText("Username                        :");
        jPanel1.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 82, 190, 33));

        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 280, 30));

        password_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        password_label.setForeground(new java.awt.Color(242, 242, 242));
        password_label.setText("Password                         :");
        jPanel1.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 121, 200, 34));

        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 280, 30));

        password_label1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        password_label1.setForeground(new java.awt.Color(242, 242, 242));
        password_label1.setText("Confirm  Password       :");
        jPanel1.add(password_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 161, -1, 34));

        confirm_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        confirm_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_passActionPerformed(evt);
            }
        });
        jPanel1.add(confirm_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 280, 30));

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Set security questions");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 200, 33));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Already have an account?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 200, 30));

        q_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        q_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q_1ActionPerformed(evt);
            }
        });
        jPanel1.add(q_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 270, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2. Which is your favourite year?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 240, 28));

        q_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        q_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q_2ActionPerformed(evt);
            }
        });
        jPanel1.add(q_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 270, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3. What is your favourite language?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 240, 29));

        q_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        q_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q_3ActionPerformed(evt);
            }
        });
        jPanel1.add(q_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 270, 30));

        create_acc_button.setBackground(new java.awt.Color(242, 242, 242));
        create_acc_button.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        create_acc_button.setText("Create new Account");
        create_acc_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        create_acc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_acc_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(create_acc_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 175, 30));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Go to login");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 107, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Create account");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 230, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("1. What is name of the girl you like?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // Username part

    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // Taking password
    }//GEN-LAST:event_passwordActionPerformed

    private void confirm_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_passActionPerformed
        // Taking password
    }//GEN-LAST:event_confirm_passActionPerformed

    private void create_acc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_acc_buttonActionPerformed
        String s1 = password.getText();
        String s2 = confirm_pass.getText();
        String s3 = username.getText();
        String q1 = q_1.getText();
        String q2 = q_2.getText();
        String q3 = q_3.getText();
        
        if(s3.equals(""))
        {
            //System.out.println("Password not matched!");
            JOptionPane.showMessageDialog(null, "You didn't insert any username!");
        }
        
        else if(s1.equals(""))
        {
            //System.out.println("Password not matched!");
            JOptionPane.showMessageDialog(null, "You didn't insert any password!");
        }
        
        else if(s2.equals(""))
        {
            //System.out.println("Password not matched!");
            JOptionPane.showMessageDialog(null, "Confirm password");
        }
        
        else if(q1.equals("")||q2.equals("")||q3.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Answer all the questions");
        }
        
        else if(s1.equals(s2))
        {
            String query = "INSERT INTO login values('"+s3+"','"+s1+"','"+q1+"','"+q2+"','"+q3+"')";
            Connection con = condb.getCon();
            
            try
            {
                Statement stm = con.createStatement();
                int x = stm.executeUpdate(query);
                
                JOptionPane.showMessageDialog(null, "Successfully created account");
                
                home_page obj = new home_page();
                obj.setVisible(true);
                setVisible(false);
            }
            
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        
        
        else { 
             //System.out.println("Password not matched!");
            JOptionPane.showMessageDialog(null, "Password not matched!");
        }
    }//GEN-LAST:event_create_acc_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        login obj = new login();
        obj.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void q_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q_2ActionPerformed

    private void q_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q_1ActionPerformed

    private void q_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm_pass;
    private javax.swing.JButton create_acc_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel password_label1;
    private javax.swing.JTextField q_1;
    private javax.swing.JTextField q_2;
    private javax.swing.JTextField q_3;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
