
import exp2.condb;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        forgot_password = new javax.swing.JButton();
        create_acc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username_label.setForeground(new java.awt.Color(242, 242, 242));
        username_label.setText("Username: ");
        jPanel1.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 33));

        password_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        password_label.setForeground(new java.awt.Color(242, 242, 242));
        password_label.setText("Password :");
        jPanel1.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, 34));

        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 250, 30));

        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 250, 30));

        Login.setBackground(new java.awt.Color(242, 242, 242));
        Login.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Login.setText("Login");
        Login.setAutoscrolls(true);
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 80, 30));

        forgot_password.setBackground(new java.awt.Color(242, 242, 242));
        forgot_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        forgot_password.setText("Forgot password");
        forgot_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        forgot_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(forgot_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 140, -1));

        create_acc.setBackground(new java.awt.Color(242, 242, 242));
        create_acc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        create_acc.setText("Create new account");
        create_acc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        create_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_accActionPerformed(evt);
            }
        });
        jPanel1.add(create_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 160, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Manager Log in");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 240, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Don't have an account?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter user information");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // Username part


    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // Taking password
    }//GEN-LAST:event_passwordActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // Login Button
        Boolean flag = false;
        input_password = password.getText();
        input_username = username.getText();
        try {
            Connection con = condb.getCon();
            Statement stm = con.createStatement();
            ResultSet retrieve_val = stm.executeQuery("SELECT username,password FROM login");
            String dat_username = "", dat_password = "";
            while (retrieve_val.next()) {
                dat_username = retrieve_val.getString(1);
                dat_password = retrieve_val.getString(2);
            }
            con.close();
            String sql_query = "select `username` , `password` from login where Sno =" + Sno;
            if (dat_username.equals(input_username) && dat_password.equals(input_password)) {
                System.out.println("Login Successfully ");
                JOptionPane.showMessageDialog(null, "Login Successfully");
                home_page obj = new home_page();
                obj.setVisible(true);
                setVisible(false);
            } else {
                System.out.println("Username or Password not Mathced!");
                JOptionPane.showMessageDialog(null, "Username or password not matched!");
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_LoginActionPerformed

    private void forgot_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_passwordActionPerformed
        forgot_password f_pass = new forgot_password();
        f_pass.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_forgot_passwordActionPerformed

    private void create_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_accActionPerformed

        try {
            Connection con = condb.getCon();
            Statement stm = con.createStatement();
            ResultSet retrieve_val = stm.executeQuery("SELECT * FROM login");
            boolean flag = false;
            while (retrieve_val.next()) flag = true;
                
            con.close();
            if (flag == false) {
                create_account new_acc = new create_account();
                new_acc.setVisible(true);
                setVisible(false);

            } else {
                //System.out.println("You already have an account");
                JOptionPane.showMessageDialog(null, "You already have an account!");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_create_accActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    //Global Variable
    public int Sno = 1;
    public String input_username;
    public String input_password;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton create_acc;
    private javax.swing.JButton forgot_password;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
